= Manual Testing for cherBook
:toc:
:toclevels: 3
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

By: `CS2103AUG2017 T16-B2`      Since: `Sep 2017`      Licence: `MIT`

== How to load the Sample Data

. Go to `{project root}\src\test\data\ManualTesting`
. Copy the `[T16-B2][cherBook]SampleData.xml` file.
. Paste the copied file inside `{project root}\src\test\data`.
. Rename the file to `addressbook.xml` in all lower case.
. The Sample data is now loaded and ready for testing.

The Sample Data contains 40 students, 24 different tags and 7 appointments in the schedule.

== Testing the features

Follow the instructions below to test cherbook's features.

=== Student Management

==== Adding Students
===== Full Command
Commands to type: `add n/Kelly Doe p/97979999 pp/97302222 e/kellyd@example.com a/665, Tampines Ave 56, #05-16 f/12S23 g/123.0 c/673349 t/track t/judo` +
Expected Results:
```
New person added: Kelly Doe Phone: 97979999 ParentPhone: 97302222 Email: kellyd@example.com Address: 665, Tampines Ave 56, #05-16 FormClass: 12S23 Grades: 123.0 PostalCode: 673349 Remark: (add a remark) Tags: [judo][track]
```
===== Using shorthand
Commands to type: `a n/Kimmy Koh p/97979222 pp/97302223 e/kimmyk@gmail.com a/311, Hougang St 2, #08-14 f/12S23 g/123.0 c/673349 t/dance t/scienceTeam` +
Expected Results:
```
New person added: Kimmy Koh Phone: 97979222 ParentPhone: 97302223 Email: kimmyk@gmail.com Address: 311, Hougang St 2, #08-14 FormClass: 12S23 Grades: 123.0 PostalCode: 673349 Remark: (add a remark) Tags: [dance][scienceTeam]
```
==== Adding Students without optional inputs
Commands to type: `add n/Zinc Nayer pp/97301122 e/zincnayer@example.com f/12S23 g/123.0 t/track t/fashion` +
Expected Results:
```
New person added: Zinc Nayer Phone: (Student phone not recorded) ParentPhone: 97301122 Email: zincnayer@example.com Address: (Address not recorded) FormClass: 12S23 Grades: 123.0 PostalCode: (Postal code not recorded) Remark: (add a remark) Tags: [track][fashion]
```
===== Using shorthand
Commands to type: `a n/Zinc Nayer pp/97301122 e/zincnayer@example.com f/12S23 g/123.0 t/track t/fashion` +
Expected Results:
```
New person added: Zinc Nayer Phone: (Student phone not recorded) ParentPhone: 97301122 Email: zincnayer@example.com Address: (Address not recorded) FormClass: 12S23 Grades: 123.0 PostalCode: (Postal code not recorded) Remark: (add a remark) Tags: [track][fashion]
```

==== Editing Students
===== Edit Name
Commands to type:
`edit 2 n/Vernice Yu` +
Expected Results:
```
Edited Person: Vernice Yu Phone: 97971197 ParentPhone: 97271231 Email: berniceyu@example.com Address: Blk 30 Lorong 3 Serangoon Gardens, #07-18 FormClass: 12SCI23 Grades: 530.0 PostalCode: 654321 Remark: Woman Tags: [colleagues][scholarship][canoeing] +
```
===== Edit Phone
Commands to type:
`edit 6 p/97971198` +
Expected Results:
```
Edited Person: Roy Balakrishnan Phone: 97971198 ParentPhone: 97112233 Email: royb@example.com Address: Blk 45 Aljunied Street 85, #11-31 FormClass: 12SCI23 Grades: 234.0 PostalCode: 999666 Remark: Mixed ethnicity Tags: [colleagues] +
```
===== Edit Parent's phone
Commands to type:
`edit 8 pp/97971100` +
Expected Results:
```
Edited Person: Mariam Mohamad Phone: 85215625 ParentPhone: 97971100 Email: mmohd@example.com Address: Blk 6 Home Gardens Street 26, #16-43 FormClass: 12SCI23 Grades: 245.0 PostalCode: 676767 Remark: Studies suffering because of CCA Tags: [needsHelp][dance] +
```
===== Edit Address
Commands to type:
`edit 10 a/Blk 50 Super Street 26, #16-43` +
Expected Results:
```
Edited Person: Laura Teh Phone: 86542453 ParentPhone: 97272011 Email: laurateh@example.com Address: Blk 50 Super Street 26, #16-43 FormClass: 12SCI23 Grades: 565.0 PostalCode: 676767 Remark: Studies suffering because of CCA Tags: [athletics] +
```
===== Using shorthand
Commands to type:
`edit 12 f/12SCI24` +
Expected Results:
```
Edited Person: Jolene Saram Phone: 85373543 ParentPhone: 97271122 Email: saramjol@example.com Address: Blk 22 Serangoon Drive 26, #16-43 FormClass: 12SCI24 Grades: 895.0 PostalCode: 676767 Remark: Top in class for math Tags: [scienceTeam] +
```

Commands to type:
`e 14 g/ 260` +
Expected Results:
```
Edited Person: Goh Qing Jing Phone: 85473617 ParentPhone: 97272222 Email: gohqingqing@example.com Address: Blk 56 Sungei Bedok 26, #16-43 FormClass: 12SCI23 Grades: 260 PostalCode: 676767 Remark: Class clown Tags: [studentCouncil] +
```

Commands to type:
`e 16 c/686868` +
Expected Results:
```
Edited Person: Dorothy Thia Phone: 93457384 ParentPhone: 97270021 Email: dorothythia@example.com Address: Blk 457 Wizard drive 26, #16-43 FormClass: 12SCI23 Grades: 295.0 PostalCode: 686868 Remark: Always blur Tags: [studentCouncil] +
```

Commands to type:
`e 18 e/johnhoe@gmail.com` +
Expected Results:
```
Edited Person: John Hoe Phone: 96575688 ParentPhone: 97112211 Email: johnhoe@gmail.com Address: SIS Building 4 Leng Kee Road #03-07 FormClass: 15APP10 Grades: 690.0 PostalCode: 159088 Remark: Head of dance CCA Tags: [studentCouncil][athletics][dance] +
```
===== Case sensitive command
Commands to type: `edIT 12 f/12SCI24` +
Expected Results:
```
Unknown command
```
//TODO: Add some Negative test cases
===== Invalid Parameters
Commands to type: `edit 15 k/invalid` +
Expected Results:
```
Invalid command format!
edit: Edits the details of the person identified by the index number used in the last person listing. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [p/PHONE] [pp/PARENTPHONE] [e/EMAIL] [a/ADDRESS] [f/FORMCLASS] [g/GRADES] [c/POSTALCODE] [t/TAG]...
Example: edit 1 p/97979797 pp/97973130 e/johndoe@example.com f/14S14 g/123.0 c/679123
```
==== Deleting Students
===== Full Command
Commands to type:
`delete 40` +
Expected Results:
```
Deleted Person: Dany Tar Phone: 81235155 ParentPhone: 97212121 Email: alexyeoh@example.com Address: Stone Street 1, #20-01 FormClass: 11WES01 Grades: 2000.0 PostalCode: 374539 Remark: Top in Class for both English and Literature Tags: [debate][studentCouncil][scholarship] +
```
===== Using shorthand
Commands to type:
`d 39` +
Expected Results:
```
Deleted Person: Marge Tyrell Phone: 84366478 ParentPhone: 97274444 Email: alexyeoh@example.com Address: High Towers Street 1, #50-01 FormClass: 11WES01 Grades: 1000.0 PostalCode: 374539 Remark: Top in Class for both English and Literature Tags: [debate][studentCouncil][scholarship +
```
Commands to type:
`d 1` +
Expected Results:
```
Deleted Person: Alex Yeoh Phone: 91234563 ParentPhone: 97273111 Email: alexyeoh@example.com Address: Blk 30 Geylang Street 29, #06-40 FormClass: 12SCI23 Grades: 940.0 PostalCode: 123456 Remark: Represented school for national track meet Tags: [track][athletics]
```
===== Case sensitive command
Commands to type: `deleTe 1` +
Expected Results:
```
Unknown command
```
===== Index out of bounds
Commands to type: `list` then `delete 100` +
Expected Results:
```
Listed all persons
```
```
The person index provided is invalid
```

==== Managing Remarks
Commands to type:
`remark 5 rm/Has joined soccer` +

Expected Results:

```
Added remark to person: Irfan Ibrahim Phone: 97978789 ParentPhone: 91231211 Email: irfan@example.com Address: Blk 47 Tampines Street 20, #17-35 FormClass: 12SCI23 Grades: 564.0 PostalCode: 999999 Remark: Has joined soccer Tags: [ScienceTeam][sailing]
```

===== Using shorthand
Commands to type:
`rm 20 rm/Quit the Army` +

Expected Results:

```
Added remark to person: John Lowe Phone: 96575628 ParentPhone: 97271111 Email: alexyeoh@example.com Address: Blk 876 Lim Chu Kang Street 92 FormClass: 15APP10 Grades: 700.0 PostalCode: 640545 Remark: Quit the army Tags: [studentCouncil][flyingClub][athletics] +
```
===== Adding with no input
Commands to type:
`rm 23 rm/` +

Expected Results:
```
Removed remark from person: Bruno Mas Phone: 97973322 ParentPhone: 97111011 Email: alexyeoh@example.com Address: 10 Biopolis Way #03-03/04 CHROMOS FormClass: 16MUS20 Grades: 979.0 PostalCode: 123456 Remark: (add a remark) Tags: [studentCouncil][band][dance]
```
===== Case Sensitive Command
Commands to type: `REMarK 2 rm/invalid` +
Expected Results:
```
Unknown command
```

==== Listing all Students
===== Full Command
Commands to type: `list`    +
Expected Results:
```
Listed all persons
```
===== Using shorthand
Commands to type: `list` then `s 19` +
Expected Results:
```
Listed all persons
```
===== Case sensitive command
Commands to type: `LiSt` +
Expected Results:
```
Unknown command
```

==== Selecting Student
===== Full Command
Commands to type: `list` then `select 37` +
Expected Results:
```
Selected Person: 37
```
===== Using shorthand
Commands to type: `list` then `s 19` +
Expected Results:
```
Listed all persons
```
```
Selected Person: 19
```
===== Index out of bounds
Commands to type: `list` then `select 100` +
Expected Results:
```
Listed all persons
```
```
The person index provided is invalid
```
===== Wrong command format (no arguments)
Commands to type: `select _` +
Expected Results:
```
Invalid command format! +
select: Selects the person identified by the index number used in the last person listing. +
Parameters: INDEX (must be a positive integer) +
Example: select 1``` +
```
[NOTE]
"_" represents a whitespace
===== Case sensitive command
Commands to type: `LiSt` +
Expected Results:
```
Unknown command
```

==== Finding by Name

===== Single keyword
Commands to type: `find john` +
Expected Results:
```
6 persons listed!
```
===== Using shorthand
Commands to type: `f john +
Expected Results:
```
6 persons listed!
```
===== Verifying OR Search
Commands to type: `find david` then `find tan` then `find david tan` +
Expected Results:
```
1 persons listed!
```
```
1 persons listed!
```
```
2 persons listed!
```
===== Case insensitive keywords
Commands to type: `find jOhN` +
Expected Results:
```
6 persons listed!
```
===== Case sensitive command
Commands to type: `fInD john` +
Expected Results:
```
Unknown command
```
===== Wrong Command Format (No arguments)
Commands to type: `find _` +
Expected Results:
```
Invalid command format! +
find: Finds all persons whose names contain any of the specified keywords (case-sensitive) and displays them as a list with index numbers. +
Parameters: KEYWORD [MORE_KEYWORDS]... +
Example: find alice bob charlie +
```
[NOTE]
"_" represents a whitespace

==== Finding Students by Tags

===== Single keyword
Commands to type: `findtags studentcouncil` +
Expected Results:
```
12 persons listed!
```
===== Using shorthand
Commands to type: `ft studentcouncil` +
Expected Results:
```
12 persons listed!
```
===== Verifying AND Search
Commands to type: `findtags studentcouncil scholarship` +
Expected Results:
```
3 persons listed!
```
===== Case insensitive keywords
Commands to type: `findtags StuDentCouNcil` +
Expected Results:
```
6 persons listed!
```
===== Case sensitive command
Commands to type: `fIndTagS StuDentCouNcil` +
Expected Results:
```
`Unknown command`
```
===== Wrong Command Format (No arguments)
Commands to type: `findtags _` +
Expected Results: +

[NOTE]
"_" represents a whitespace

```
Invalid command format! +
`findtags: Finds all persons whose tags contain any of the specified keywords (case-insensitive) and displays them as a list with index numbers. +
Parameters: KEYWORD [MORE_KEYWORDS]... +
Example: findtags friends owesMoney` +
```


=== Schedule Management
[NOTE]
Adding, Viewing and Deleting schedules is to be followed sequentially.

==== Add appointments
Commands to type: `addschedule 29 s/25 november 8pm` +
Expected Results:
```
Added Morty Smith to consultations schedule on Sat Nov 25 20:00:00 SGT 2017.
Use 'viewsch' or 'viewschedule' command to view all your schedules.
```
===== Using shorthand
Commands to type: `addsch 2 s/26 november 6pm` +
Expected Results:
```
Added Bernice Yu to consultations schedule on Sun Nov 26 18:00:00 SGT 2017.
Use 'viewsch' or 'viewschedule' command to view all your schedules.
```
===== Using Natural Language Parsing
Commands to type: `addschedule 6 s/christmas 2pm` +
Expected Results:
```
Added Roy Balakrishnan to consultations schedule on Mon Dec 25 14:00:00 SGT 2017.
Use 'viewsch' or 'viewschedule' command to view all your schedules.
```
===== Wrong Command Format (No arguments)
Commands to type: `addsch 5 s/` +
Expected Results:
```
Invalid command format!
addschedule: Schedules the selected indexed person to a consultation timeslot.
Parameters: INDEX (must be a positive integer)
Example: addschedule 1 s/tomorrow 6.30pm
```
===== Wrong Command Format (Unparseable string)
Commands to type: `addsch 5 s/this string is not parseable` +
Expected Results:
```
Invalid command format!
addschedule: Schedules the selected indexed person to a consultation timeslot.
Parameters: INDEX (must be a positive integer)
Example: addschedule 1 s/tomorrow 6.30pm
```

==== Viewing appointments
===== Using Schedule
Commands to type: `viewschedule` +
Expected Results:
```
Listed your schedule.
[Schedule is fixed with Morty Smith on Sat Nov 25 20:00:00 SGT 2017
 Schedule is fixed with Bernice Yu on Sun Nov 26 18:00:00 SGT 2017
 Schedule is fixed with Roy Balakrishnan on Mon Dec 25 14:00:00 SGT 2017]
```

===== Using shorthand
Commands to type: `viewsch` +
Expected Results:
```
Listed your schedule.
[Schedule is fixed with Morty Smith on Sat Nov 25 20:00:00 SGT 2017
 Schedule is fixed with Bernice Yu on Sun Nov 26 18:00:00 SGT 2017
 Schedule is fixed with Roy Balakrishnan on Mon Dec 25 14:00:00 SGT 2017]
```

==== Deleting appointments
===== Delete with single index
Commands to type: `deleteschedule 1` +
Expected Results:
```
Deleted Schedule: Schedule is fixed with Morty Smith on Sat Nov 25 20:00:00 SGT 2017
```
===== Using shorthand
Commands to type: `deletesch 1` +
Expected Results:
```
Deleted Schedule: Schedule is fixed with Bernice Yu on Sun Nov 26 18:00:00 SGT 2017
```
===== Index out of bounds
Commands to type: `deleteschedule 100` +
Expected Results:
```
The schedule index provided is invalid
```
===== Index Zero
Commands to type: `deletesch 0` +
Expected Results:
```
Invalid command format!
deleteschedule: Deletes the schedule identified by the index number.
Parameters: INDEX (must be a positive integer)
Example: deleteschedule 1
```

==== Sorting all cherBook Students
===== Full Command
Commands to type: `sort` +
Expected Results: +
```
All contacts are sorted alphabetically by name.
```
===== Using shorthand
Commands to type: `st` +
Expected Results:
```
All contacts are sorted alphabetically by name.
```
==== Listing all cherBook Students
===== Full Command
Commands to type: `list` +
Expected Results:
```
Listed all persons
```
===== Using shorthand
Commands to type: `l`
Expected Results: +
```
Listed all persons
```

=== User Interface Management

==== Opening Help Window
===== Full Command
Commands to type: `help` +
Expected Results: +
```
Opened help window.
```
===== Case sensitive command
Commands to type: `helP` +
Expected Results:
```
`Unknown command`
```

==== Switching to and from Home Page
Commands to type: +
`home`

Expected Results: +

```
Welcome Home
```

==== Switching between tabs in the Graph Panel
Commands to type: +
`Tab 1`

Expected Results: +

```
Selected Tab: 1
```

Commands to type: +
`Tab 2`

Expected Results: +
```
Selected Tab: 2
```
== known Bugs

=== Deleting wrong person
Commands to type: +
`find david` +
`delete 1` +
`list` +
`undo` +
`redo`

Expected Results: +
`1 persons listed!` +
`Deleted Person: David Li Phone: 85473617 ParentPhone: 91113011 Email: lidavid@example.com Address: Blk 436 Serangoon Gardens Street 26, #16-43 FormClass: 12SCI23 Grades: 245.0 PostalCode: 676767 Remark: Studies suffering because of CCA Tags: [needsHelp][studentCouncil]` +
`Listed all persons` +
`Undo success!` (David is back in the list) +
`Redo success!` (First person in the list is deleted, not david who is the third)
